language: ja-jp

# Supported: PermissionsEx, SuperPerms
Permission: "PermissionsEx"

#-=-=-=-=-=-=-=-=-=-=-#
# GeoIP Config        #
#-=-=-=-=-=-=-=-=-=-=-#
UseGeoIP: true
UseCityDB: true
UseSimpleFormatOnJoin: true
DownloadMissingDB: true
CountryDB: "http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz"
CityDB: "http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz"
    
ConfigVersion: 1